version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://brapshield.fartaxa.com
    ports:
      - "5173:5173"
    restart: unless-stopped